---
name:                 build and deploy - github2

on:
  push:
    branches:         [ master ]
  pull_request:
    branches:         [ master ]

jobs:
  build-and-deplpy:

    runs-on:          ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name:           Checkout ğŸ›ï¸
      uses:           actions/checkout@v2
          
    - name:           Setup node
      uses:           actions/setup-node@v1

    - name:           Install packages and build
      run:            |
         npm ci
         npm run build
         npm run export

    - name:           adding noJekyll
      run:            touch ./out/.nojekyll

    - name:           Deploy ğŸš€ 
      uses:           JamesIves/github-pages-deploy-action@v4.2.5
      with:
        node-version: ${{ matrix.node-version }}
        branch:     gh-pages # The branch the action should deploy to.
        folder:     out # The folder the action should deploy.
